steps:
  - name: maven:3.3-jdk-8
    entrypoint: mvn
    args: ['package','-Dmaven.test.skip=true']
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "us-docker.pkg.dev/my-test-project-dev-434519/test-repo/gcs-bq-loader", "--build-arg=JAR_FILE=target/gcs-bq-loader-1.0.0-SNAPSHOT.jar", "."]
images: ["us-docker.pkg.dev/my-test-project-dev-434519/test-repo/gcs-bq-loader"]