steps:
  - name: maven:3.3-jdk-8
    entrypoint: mvn
    args: ['package','-Dmaven.test.skip=true']
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "europe-north1-docker.pkg.dev/my-test-project-dev-434519/test-repo/docker-test", "--build-arg=JAR_FILE=target/gcs-bq-sample-1.0.0-SNAPSHOT.jar", "."]
images: ["europe-north1-docker.pkg.dev/my-test-project-dev-434519/test-repo/docker-test"]